version: '3'
services:
  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: ruby app.rb -o 0.0.0.0
    volumes:
      - .:/tcf-phoenix
    ports:
      - "4568:4568"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
