version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: ruby app.rb -o 0.0.0.0
    volumes:
      - .:/tcf-phoenix
    ports:
      - "4567:4567"
    depends_on:
      - redis
    environment:
      #- REDIS_URL=redis://redis
      - REDIS_URL=redis-13266.c80.us-east-1-2.ec2.cloud.redislabs.com:13266
